#!/usr/bin/env php
<?php

if (php_sapi_name() !== 'cli') {
	exit;
}

// Register Application Space
define('BEAR', $_SERVER['BEAR_ENV'] ?? 'production');

// Includes Constants
require_once __DIR__ . '/config/constants.php';
require_once __DIR__ . '/vendor/autoload.php';

// List all Command
use Bear\App\Command\TestCommand;
use nguyenanhung\Console\Application\PhpDiApplication;

$app = new PhpDiApplication(ENV_APP_NAME, '1.0.0');

// Routes list Command
$app->command(parseExpressionOptions('greet', [
		'u|upper',
		'r|randomFaker'
]), TestCommand::class)->descriptions(TestCommand::$desc, TestCommand::$optionsInfo);

try {
	$app->run();
} catch (Exception $e) {
	echo $e->getMessage() . PHP_EOL;
}
