# GitHub Action for PHP Package HungNG Command Skeleton
name: Testing PHP Package HungNG Command Skeleton
on: [ push, pull_request ]
jobs:
    build:
        strategy:
            matrix:
                operating-system: [ ubuntu-latest, windows-latest, macos-latest ]
                php-versions: [ '7.4', '8.0', '8.1', '8.2' ]
        runs-on: ${{ matrix.operating-system }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Setup PHP, with composer and extensions
                uses: shivammathur/setup-php@v2 # From https://github.com/shivammathur/setup-php
                with:
                    php-version: ${{ matrix.php-versions }}
                    extensions: mbstring, intl, curl, json, openssl, iconv, pdo, pdo_mysql, mysqli, xml, sockets
                    coverage: xdebug #optional
            -   name: Get composer cache directory
                id: composercache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"
            -   name: Cache composer dependencies
                uses: actions/cache@v2
                with:
                    path: ${{ steps.composercache.outputs.dir }}
                    # Use composer.json for key, if composer.lock is not committed.
                    # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ runner.os }}-composer-
            -   name: Install dependencies
                run: composer install --no-progress --prefer-dist --optimize-autoloader
            -   name: Start Test Command
                run: php bear greet Bear --upper --randomFaker